### ISSUE TITLE
wget retries param error no = required

### ISSUE THREAD

**Issue by alanmbarr** [cfpb/HMDA_Data_Science_Kit#50]
I did not see a contributing.md I can fix this myself but wanted to ask if you're open to pull requests? essentially wget throws an error because the [command line args](https://github.com/cfpb/HMDA_Data_Science_Kit/blob/master/download_scripts/download_hmda.sh#L200) is -t 10 and not -t=10 at least with my version of wget

**Comment by Kibrael** [comment]
Hello, apologies for not seeing this post sooner.

We are open to pull requests. I'll look into setting up a contributing.md file in the near future.
